Add OTP application
Yubico/yubioath-flutter pull request #1302
Opened 2023-12-13 16:27 UTC by elibon99

This PR mainly implements support for the OTP application. In addition, it also introduces a couple of UI changes related to input field validation.

2023-12-14 12:47 UTC, AdamVe approved these changes
LGTM!

2023-12-14 14:01 UTC, dainnilsson requested changes

2023-12-14 14:24 UTC, dainnilsson commented on lib/desktop/otp/state.dart
> +      ref.watch(rpcProvider).requireValue, devicePath, ['ccid', 'yubiotp']),
Only newer keys have `yubiotp` exposed over CCID. All have it over OTP. One needs to be used as a fallback to the other.

2023-12-15 08:46 UTC, AdamVe approved these changes
LGTM

2023-12-15 12:05 UTC, dainnilsson approved these changes

2023-12-15 13:41 UTC, merged