Tests for all basic OTP functionality of a Yubikey
Yubico/yubioath-flutter pull request #1382
Opened 2024-02-08 13:55 UTC by jokkon

All basic OTP functionality has integration tests. To verify please run tests in otp_test.dart and see that all tests pass.

2024-02-08 14:05 UTC, AdamVe requested changes
There are some details we can improve, see my comments

2024-02-08 14:05 UTC, AdamVe commented on lib/otp/keys.dart
> +
remove this commented line

2024-02-08 14:05 UTC, AdamVe commented on lib/otp/views/configure_chalresp_dialog.dart
> +import '../keys.dart';
remove this and use the prefix (instead of `generateSecretKey` use `keys.generateSecretKey` and so on)

2024-02-08 14:05 UTC, AdamVe commented on lib/otp/views/configure_static_dialog.dart
> +import '../keys.dart';
remove this and use the prefix (instead of generateSecretKey use keys.generateSecretKey and so on)

2024-02-08 14:05 UTC, AdamVe commented on lib/otp/views/configure_yubiotp_dialog.dart
> +import '../keys.dart';
remove this and use the prefix (instead of useSerial use keys.useSerial and so on)

2024-02-08 19:49 UTC, jokkon commented
All @AdamVe improvements have been commited.

2024-02-09 07:37 UTC, AdamVe approved these changes
LGTM

2024-02-09 12:29 UTC, merged